#!/bin/bash
if [[ "$1" == "" || "$1" == "-h" || "$1" == "--help" ]]; then
    echo "Usage: $0 [ -q <queue> ] [ directory ] "
    echo "Will look in the specified directory (or in the current one if none is specified),  "
    echo "list failed jobs and print the cmgResubChunk commands to resubmit them."
    echo "The default queue is 8nh" 
    exit 1;
fi

TERSE=/bin/false
if [[ "$1" == "-T" ]]; then 
    TERSE=/bin/true; shift; 
fi;

LSFL=0
if [[ "$1" == "-d" ]]; then
    LSFL=1; shift; 
    $TERSE || echo "# Will check for a LSFJOB_ dir "
fi;

F=JSONAnalyzer/JSON.pck
if [[ "$1" == "-t" ]]; then
    F=$2; shift; shift;
    $TERSE || echo "# Will test for the presence of file $F "
fi;

LOC=0
if [[ "$1" == "-l" ]]; then
    LOC=1; shift;
fi;

P=false
if [[ "$1" == "-p" ]]; then
    $TERSE || echo "# Will also check for null pck files"
    P=true; shift;
fi;

Q=8nh
if [[ "$1" == "-q" ]]; then
    Q=$2; shift; shift;
fi;

Z=0
if [[ "$1" == "-z" ]]; then
    if echo $F | grep -q "\.root$"; then
        $TERSE || echo "# Will also check if rootfiles $F are zombies or not"
        Z=1; shift;
    else
        $TERSE || echo "# Error: can't test for zombies (-z) if the specified file to test is not a rootfile (-t $F)";
        exit 1;
    fi;
fi;


BASE="";
if [[ "$1" != "" && "$1" != "." ]]; then
    test -d $1 && cd $1 && BASE="$PWD/";
fi

$TERSE || echo "# Will print out the commands to resubmit the chunks that failed "
for D in *_Chunk[0-9]*; do
    PCKBAD=false
    ${P} && find $D -name '*.pck' -empty | grep -q pck && PCKBAD=true; 
    if test \! -s $D/$F || $PCKBAD; then
        if [[ "${LSFL}" == "0"  ]] || find $D -maxdepth 1 -type d -name 'LSFJOB_*' | grep -q LSFJ || test -f $D/submission_failed ; then
            if [[ "$LOC" == "1" ]]; then
                echo "cmgRunChunkLocally ${BASE}${D} ";
	    else
		echo "cmgResubChunk -q $Q ${BASE}${D} ";
            fi
        else
            $TERSE || echo "# Chunk ${BASE}${D} does not have a LSFJOB directory, maybe still running? "; 
        fi;
    fi;
done;
if [[ "$Z" != "0" ]]; then
    $TERSE || echo "# Testing for zombies";
    for Z in $(cmgListZombies  "*_Chunk[0-9]*/$F"); do
        if test -s $Z; then # empty files have already been found
            D=${Z%%/*};
            if [[ "$LOC" == "1" ]]; then
                echo "cmgRunChunkLocally ${BASE}${D}     # zombie"; 
            else
                echo "cmgResubChunk -q $Q ${BASE}${D}    # zombie";
            fi
        fi;
    done
fi;
