#!/bin/bash
WORKDIR=$PWD
export HOMEDIR=$1; shift
export SCRAM_ARCH=$1; shift
LOG="runBatch.log.${LSB_JOBID}"
cd $HOMEDIR;
eval $(scramv1 runtime -sh)
ulimit -s unlimited
ulimit -c 0
cp -s $PWD/*.{py,sh,cc} $WORKDIR/
cd $WORKDIR
echo "## Home dir is $HOMEDIR"  >  $LOG
echo "## Executing $*"  >> $LOG
echo "## Starting at $(date)"  >> $LOG
$* 2>&1 | tee -a $LOG > /dev/null
echo "## Done at $(date)" >> $LOG
gzip ${LOG}
tar cvf out.${LSB_JOBID}.tar ${LOG}.gz plots
cp out.${LSB_JOBID}.tar  $HOMEDIR
