tauIDs = [
    # MVA 5 still available, but we probably don't need it anymore
    # ('againstElectron{wp}MVA5', ['VLoose', 'Loose', 'Medium', 'Tight', 'VTight']),
    # 'againstElectronMVA5category',
    # 'againstElectronMVA5raw',
    ('againstElectron{wp}MVA6', ['VLoose', 'Loose', 'Medium', 'Tight', 'VTight']),
    'againstElectronMVA6category',
    'againstElectronMVA6Raw',
    ('againstMuon{wp}3', ['Loose', 'Tight']),
    'byCombinedIsolationDeltaBetaCorrRaw3Hits',
    'byIsolationMVArun2v1DBoldDMwLTraw',
    'byIsolationMVArun2v1DBnewDMwLTraw',
    'byIsolationMVArun2v1PWoldDMwLTraw',
    'byIsolationMVArun2v1PWnewDMwLTraw',
    'byIsolationMVArun2v1DBdR03oldDMwLTraw',
    ('by{wp}CombinedIsolationDeltaBetaCorr3Hits', ['Loose', 'Medium', 'Tight']),
    ('by{wp}IsolationMVArun2v1DBoldDMwLT', ['VLoose', 'Loose', 'Medium', 'Tight', 'VTight', 'VVTight']),
    ('by{wp}IsolationMVArun2v1DBnewDMwLT', ['VLoose', 'Loose', 'Medium', 'Tight', 'VTight', 'VVTight']),
    ('by{wp}IsolationMVArun2v1PWoldDMwLT', ['VLoose', 'Loose', 'Medium', 'Tight', 'VTight', 'VVTight']),
    ('by{wp}IsolationMVArun2v1PWnewDMwLT', ['VLoose', 'Loose', 'Medium', 'Tight', 'VTight', 'VVTight']),
    ('by{wp}IsolationMVArun2v1DBdR03oldDMwLT', ['VLoose', 'Loose', 'Medium', 'Tight', 'VTight', 'VVTight']),
    'chargedIsoPtSum',
    'chargedIsoPtSumdR03',
    'decayModeFinding',
    'decayModeFindingNewDMs',
    'neutralIsoPtSum',
    'neutralIsoPtSumdR03',
    'puCorrPtSum',
    'neutralIsoPtSumWeight',
    'footprintCorrection',
    'footprintCorrectiondR03',
    'photonPtSumOutsideSignalCone',
    'photonPtSumOutsideSignalConedR03',
]
