tauIDs = [
    ('againstElectron{wp}MVA5', ['VLoose', 'Loose', 'Medium', 'Tight', 'VTight']),
    'againstElectronMVA5category',
    'againstElectronMVA5raw',
    ('againstMuon{wp}3', ['Loose', 'Tight']),
    'byCombinedIsolationDeltaBetaCorrRaw3Hits',
    'byIsolationMVA3newDMwLTraw',
    'byIsolationMVA3oldDMwLTraw',
    ('by{wp}CombinedIsolationDeltaBetaCorr3Hits', ['Loose', 'Medium', 'Tight']),
    ('by{wp}IsolationMVA3newDMwLT', ['VLoose', 'Loose', 'Medium', 'Tight', 'VTight', 'VVTight']),
    ('by{wp}IsolationMVA3oldDMwLT', ['VLoose', 'Loose', 'Medium', 'Tight', 'VTight', 'VVTight']),
    'chargedIsoPtSum',
    'decayModeFinding',
    'decayModeFindingNewDMs',
    'neutralIsoPtSum',
    'puCorrPtSum',
    ('by{wp}PileupWeightedIsolation3Hits', ['Loose', 'Medium', 'Tight']),
    'byPileupWeightedIsolationRaw3Hits',
    'neutralIsoPtSumWeight',
    'footprintCorrection',
    'photonPtSumOutsideSignalCone',
]
