// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/home/users/e/l/elfaham/CMSSW_10_4_0/src/CMGTools/TTHAnalysis/python/plotter/functions.cc";

#endif
