#!/bin/bash
#command for skimming trees 
#2016 command produced testing
python skimTreesNew.py -P /nfs/user/pvischia/tth/v5pre/NanoTrees_TTH_300519_v5pre_skim2LSS/2016 --skim-friends --Fs {P}/0_jmeUnc_v1 --Fs {P}/1_lepJetBTagDeepFlav_v1 --Fs {P}/2_triggerSequence_v1 --Fs {P}/2_triggerSequence_v2 --Fs {P}/3_recleaner_v1 --Fs {P}/3_recleaner_v2 --FMCs {P}/4_btag --FMCs {P}/4_btag_v2 --FMCs {P}/4_leptonSFs_v0 --FMCs {P}/0_mcFlags_v0 --Fs {P}/6_BDThtt --Fs {P}/5_higgsDecay --Fs {P}/2lss_Top-tagged_16 --Fs {P}/2lss_NoTop-tagged_16 --mcc ttH-multilepton/lepchoice-ttH-FO.txt -L ttH-multilepton/functionsTTH.cc --mcc ttH-multilepton/mcc-METFixEE2017.txt -p ttH --tree NanoAOD --elist skimwork ttH-multilepton/mca-2lss-mc.txt ttH-multilepton/2lss_tight.txt ./testing

#2017 command produced testing_17
#python skimTreesNew.py -P /nfs/user/pvischia/tth/v5pre/NanoTrees_TTH_300519_v5pre_skim2LSS/2017 --skim-friends --Fs {P}/0_jmeUnc_v1 --Fs {P}/1_lepJetBTagDeepFlav_v1 --Fs {P}/2_triggerSequence_v1 --Fs {P}/2_triggerSequence_v2 --Fs {P}/3_recleaner_v1 --Fs {P}/3_recleaner_v2 --FMCs {P}/4_btag --FMCs {P}/4_btag_v2 --FMCs {P}/4_leptonSFs_v0 --FMCs {P}/0_mcFlags_v0 --Fs {P}/6_BDThtt --Fs {P}/5_higgsDecay --Fs {P}/2lss_Top-tagged_17 --Fs {P}/2lss_NoTop-tagged_17 --mcc ttH-multilepton/lepchoice-ttH-FO.txt -L ttH-multilepton/functionsTTH.cc --mcc ttH-multilepton/mcc-METFixEE2017.txt -p ttH --tree NanoAOD ttH-multilepton/mca-2lss-mc.txt ttH-multilepton/2lss_tight.txt ./testing_17

#2018 command produced testing_18
#python skimTreesNew.py -P /nfs/user/pvischia/tth/v5pre/NanoTrees_TTH_300519_v5pre_skim2LSS/2018 --skim-friends --Fs {P}/0_jmeUnc_v1 --Fs {P}/1_lepJetBTagDeepFlav_v1 --Fs {P}/2_triggerSequence_v1 --Fs {P}/2_triggerSequence_v2 --Fs {P}/3_recleaner_v1 --Fs {P}/3_recleaner_v2 --FMCs {P}/4_btag --FMCs {P}/4_btag_v2 --FMCs {P}/4_leptonSFs_v0 --FMCs {P}/0_mcFlags_v0 --Fs {P}/6_BDThtt --Fs {P}/5_higgsDecay --Fs {P}/2lss_Top-tagged_18 --Fs {P}/2lss_NoTop-tagged_18 --mcc ttH-multilepton/lepchoice-ttH-FO.txt -L ttH-multilepton/functionsTTH.cc --mcc ttH-multilepton/mcc-METFixEE2017.txt -p ttH --tree NanoAOD ttH-multilepton/mca-2lss-mc.txt ttH-multilepton/2lss_tight.txt ./testing_18

#TODO
#python skimTreesNew.py -P /nfs/user/pvischia/tth/v5pre/NanoTrees_TTH_300519_v5pre_skim2LSS/2016 --skim-friends --Fs {P}/0_jmeUnc_v1 --Fs {P}/1_lepJetBTagDeepFlav_v1 --Fs {P}/2_triggerSequence_v1 --Fs {P}/2_triggerSequence_v2 --Fs {P}/3_recleaner_v1 --Fs {P}/3_recleaner_v2 --FMCs {P}/4_btag --FMCs {P}/4_btag_v2 --FMCs {P}/4_leptonSFs_v0 --FMCs {P}/0_mcFlags_v0 --Fs {P}/6_BDThtt --Fs {P}/5_higgsDecay --Fs {P}/2lss_Top-tagged_16 --Fs {P}/2lss_NoTop-tagged_16 --mcc ttH-multilepton/lepchoice-ttH-FO.txt -L ttH-multilepton/functionsTTH.cc --mcc ttH-multilepton/mcc-METFixEE2017.txt -p ttH --tree NanoAOD ttH-multilepton/mca-2lss-mc.txt ./2lss_tight_1.txt ./testing_diff_cuts_1

#python skimTreesNew.py -P /nfs/user/pvischia/tth/v5pre/NanoTrees_TTH_300519_v5pre_skim2LSS/2016 --skim-friends --Fs {P}/0_jmeUnc_v1 --Fs {P}/1_lepJetBTagDeepFlav_v1 --Fs {P}/2_triggerSequence_v1 --Fs {P}/2_triggerSequence_v2 --Fs {P}/3_recleaner_v1 --Fs {P}/3_recleaner_v2 --FMCs {P}/4_btag --FMCs {P}/4_btag_v2 --FMCs {P}/4_leptonSFs_v0 --FMCs {P}/0_mcFlags_v0 --Fs {P}/6_BDThtt --Fs {P}/5_higgsDecay --Fs {P}/2lss_Top-tagged_16 --Fs {P}/2lss_NoTop-tagged_16 --mcc ttH-multilepton/lepchoice-ttH-FO.txt -L ttH-multilepton/functionsTTH.cc --mcc ttH-multilepton/mcc-METFixEE2017.txt -p ttH --tree NanoAOD ttH-multilepton/mca-2lss-mc.txt ./2lss_tight_2.txt ./testing_diff_cuts_2

#python skimTreesNew.py -P /nfs/user/pvischia/tth/v5pre/NanoTrees_TTH_300519_v5pre_skim2LSS/2016 --skim-friends --Fs {P}/0_jmeUnc_v1 --Fs {P}/1_lepJetBTagDeepFlav_v1 --Fs {P}/2_triggerSequence_v1 --Fs {P}/2_triggerSequence_v2 --Fs {P}/3_recleaner_v1 --Fs {P}/3_recleaner_v2 --FMCs {P}/4_btag --FMCs {P}/4_btag_v2 --FMCs {P}/4_leptonSFs_v0 --FMCs {P}/0_mcFlags_v0 --Fs {P}/6_BDThtt --Fs {P}/5_higgsDecay --Fs {P}/2lss_Top-tagged_16 --Fs {P}/2lss_NoTop-tagged_16 --mcc ttH-multilepton/lepchoice-ttH-FO.txt -L ttH-multilepton/functionsTTH.cc --mcc ttH-multilepton/mcc-METFixEE2017.txt -p ttH --tree NanoAOD ttH-multilepton/mca-2lss-mc.txt ./2lss_tight_3.txt ./testing_diff_cuts_3

#python skimTreesNew.py -P /nfs/user/pvischia/tth/v5pre/NanoTrees_TTH_300519_v5pre_skim2LSS/2016 --skim-friends --Fs {P}/0_jmeUnc_v1 --Fs {P}/1_lepJetBTagDeepFlav_v1 --Fs {P}/2_triggerSequence_v1 --Fs {P}/2_triggerSequence_v2 --Fs {P}/3_recleaner_v1 --Fs {P}/3_recleaner_v2 --FMCs {P}/4_btag --FMCs {P}/4_btag_v2 --FMCs {P}/4_leptonSFs_v0 --FMCs {P}/0_mcFlags_v0 --Fs {P}/6_BDThtt --Fs {P}/5_higgsDecay --Fs {P}/2lss_Top-tagged_16 --Fs {P}/2lss_NoTop-tagged_16 --mcc ttH-multilepton/lepchoice-ttH-FO.txt -L ttH-multilepton/functionsTTH.cc --mcc ttH-multilepton/mcc-METFixEE2017.txt -p ttH --tree NanoAOD ttH-multilepton/mca-2lss-mc.txt ./2lss_tight_4.txt ./testing_diff_cuts_4

#python skimTreesNew.py -P /nfs/user/pvischia/tth/v5pre/NanoTrees_TTH_300519_v5pre_skim2LSS/2016 --skim-friends --Fs {P}/0_jmeUnc_v1 --Fs {P}/1_lepJetBTagDeepFlav_v1 --Fs {P}/2_triggerSequence_v1 --Fs {P}/2_triggerSequence_v2 --Fs {P}/3_recleaner_v1 --Fs {P}/3_recleaner_v2 --FMCs {P}/4_btag --FMCs {P}/4_btag_v2 --FMCs {P}/4_leptonSFs_v0 --FMCs {P}/0_mcFlags_v0 --Fs {P}/6_BDThtt --Fs {P}/5_higgsDecay --Fs {P}/2lss_Top-tagged_16 --Fs {P}/2lss_NoTop-tagged_16 --mcc ttH-multilepton/lepchoice-ttH-FO.txt -L ttH-multilepton/functionsTTH.cc --mcc ttH-multilepton/mcc-METFixEE2017.txt -p ttH --tree NanoAOD ttH-multilepton/mca-2lss-mc.txt ./2lss_tight_5.txt ./testing_diff_cuts_5

#python skimTreesNew.py -P /nfs/user/pvischia/tth/v5pre/NanoTrees_TTH_300519_v5pre_skim2LSS/2016 --skim-friends --Fs {P}/0_jmeUnc_v1 --Fs {P}/1_lepJetBTagDeepFlav_v1 --Fs {P}/2_triggerSequence_v1 --Fs {P}/2_triggerSequence_v2 --Fs {P}/3_recleaner_v1 --Fs {P}/3_recleaner_v2 --FMCs {P}/4_btag --FMCs {P}/4_btag_v2 --FMCs {P}/4_leptonSFs_v0 --FMCs {P}/0_mcFlags_v0 --Fs {P}/6_BDThtt --Fs {P}/5_higgsDecay --Fs {P}/2lss_Top-tagged_16 --Fs {P}/2lss_NoTop-tagged_16 --mcc ttH-multilepton/lepchoice-ttH-FO.txt -L ttH-multilepton/functionsTTH.cc --mcc ttH-multilepton/mcc-METFixEE2017.txt -p ttH --tree NanoAOD ttH-multilepton/mca-2lss-mc.txt ./2lss_tight_6.txt ./testing_diff_cuts_6

#python skimTreesNew.py -P /nfs/user/pvischia/tth/v5pre/NanoTrees_TTH_300519_v5pre_skim2LSS/2016 --skim-friends --Fs {P}/0_jmeUnc_v1 --Fs {P}/1_lepJetBTagDeepFlav_v1 --Fs {P}/2_triggerSequence_v1 --Fs {P}/2_triggerSequence_v2 --Fs {P}/3_recleaner_v1 --Fs {P}/3_recleaner_v2 --FMCs {P}/4_btag --FMCs {P}/4_btag_v2 --FMCs {P}/4_leptonSFs_v0 --FMCs {P}/0_mcFlags_v0 --Fs {P}/6_BDThtt --Fs {P}/5_higgsDecay --Fs {P}/2lss_Top-tagged_16 --Fs {P}/2lss_NoTop-tagged_16 --mcc ttH-multilepton/lepchoice-ttH-FO.txt -L ttH-multilepton/functionsTTH.cc --mcc ttH-multilepton/mcc-METFixEE2017.txt -p ttH --tree NanoAOD ttH-multilepton/mca-2lss-mc.txt ./2lss_tight_7.txt ./testing_diff_cuts_7

#python skimTreesNew.py -P /nfs/user/pvischia/tth/v5pre/NanoTrees_TTH_300519_v5pre_skim2LSS/2016 --skim-friends --Fs {P}/0_jmeUnc_v1 --Fs {P}/1_lepJetBTagDeepFlav_v1 --Fs {P}/2_triggerSequence_v1 --Fs {P}/2_triggerSequence_v2 --Fs {P}/3_recleaner_v1 --Fs {P}/3_recleaner_v2 --FMCs {P}/4_btag --FMCs {P}/4_btag_v2 --FMCs {P}/4_leptonSFs_v0 --FMCs {P}/0_mcFlags_v0 --Fs {P}/6_BDThtt --Fs {P}/5_higgsDecay --Fs {P}/2lss_Top-tagged_16 --Fs {P}/2lss_NoTop-tagged_16 --mcc ttH-multilepton/lepchoice-ttH-FO.txt -L ttH-multilepton/functionsTTH.cc --mcc ttH-multilepton/mcc-METFixEE2017.txt -p ttH --tree NanoAOD ttH-multilepton/mca-2lss-mc.txt ./2lss_tight_8.txt ./testing_diff_cuts_8

#python skimTreesNew.py -P /nfs/user/pvischia/tth/v5pre/NanoTrees_TTH_300519_v5pre_skim2LSS/2016 --skim-friends --Fs {P}/0_jmeUnc_v1 --Fs {P}/1_lepJetBTagDeepFlav_v1 --Fs {P}/2_triggerSequence_v1 --Fs {P}/2_triggerSequence_v2 --Fs {P}/3_recleaner_v1 --Fs {P}/3_recleaner_v2 --FMCs {P}/4_btag --FMCs {P}/4_btag_v2 --FMCs {P}/4_leptonSFs_v0 --FMCs {P}/0_mcFlags_v0 --Fs {P}/6_BDThtt --Fs {P}/5_higgsDecay --Fs {P}/2lss_Top-tagged_16 --Fs {P}/2lss_NoTop-tagged_16 --mcc ttH-multilepton/lepchoice-ttH-FO.txt -L ttH-multilepton/functionsTTH.cc --mcc ttH-multilepton/mcc-METFixEE2017.txt -p ttH --tree NanoAOD ttH-multilepton/mca-2lss-mc.txt ./2lss_tight_9.txt ./testing_diff_cuts_9

#python skimTreesNew.py -P /nfs/user/pvischia/tth/v5pre/NanoTrees_TTH_300519_v5pre_skim2LSS/2016 --skim-friends --Fs {P}/0_jmeUnc_v1 --Fs {P}/1_lepJetBTagDeepFlav_v1 --Fs {P}/2_triggerSequence_v1 --Fs {P}/2_triggerSequence_v2 --Fs {P}/3_recleaner_v1 --Fs {P}/3_recleaner_v2 --FMCs {P}/4_btag --FMCs {P}/4_btag_v2 --FMCs {P}/4_leptonSFs_v0 --FMCs {P}/0_mcFlags_v0 --Fs {P}/6_BDThtt --Fs {P}/5_higgsDecay --Fs {P}/2lss_Top-tagged_16 --Fs {P}/2lss_NoTop-tagged_16 --mcc ttH-multilepton/lepchoice-ttH-FO.txt -L ttH-multilepton/functionsTTH.cc --mcc ttH-multilepton/mcc-METFixEE2017.txt -p ttH --tree NanoAOD ttH-multilepton/mca-2lss-mc.txt ./2lss_tight_10.txt ./testing_diff_cuts_10

#python skimTreesNew.py -P /nfs/user/pvischia/tth/v5pre/NanoTrees_TTH_300519_v5pre_skim2LSS/2016 --skim-friends --Fs {P}/0_jmeUnc_v1 --Fs {P}/1_lepJetBTagDeepFlav_v1 --Fs {P}/2_triggerSequence_v1 --Fs {P}/2_triggerSequence_v2 --Fs {P}/3_recleaner_v1 --Fs {P}/3_recleaner_v2 --FMCs {P}/4_btag --FMCs {P}/4_btag_v2 --FMCs {P}/4_leptonSFs_v0 --FMCs {P}/0_mcFlags_v0 --Fs {P}/6_BDThtt --Fs {P}/5_higgsDecay --Fs {P}/2lss_Top-tagged_16 --Fs {P}/2lss_NoTop-tagged_16 --mcc ttH-multilepton/lepchoice-ttH-FO.txt -L ttH-multilepton/functionsTTH.cc --mcc ttH-multilepton/mcc-METFixEE2017.txt -p ttH --tree NanoAOD ttH-multilepton/mca-2lss-mc.txt ./2lss_tight_11.txt ./testing_diff_cuts_11

#python skimTreesNew.py -P /nfs/user/pvischia/tth/v5pre/NanoTrees_TTH_300519_v5pre_skim2LSS/2016 --skim-friends --Fs {P}/0_jmeUnc_v1 --Fs {P}/1_lepJetBTagDeepFlav_v1 --Fs {P}/2_triggerSequence_v1 --Fs {P}/2_triggerSequence_v2 --Fs {P}/3_recleaner_v1 --Fs {P}/3_recleaner_v2 --FMCs {P}/4_btag --FMCs {P}/4_btag_v2 --FMCs {P}/4_leptonSFs_v0 --FMCs {P}/0_mcFlags_v0 --Fs {P}/6_BDThtt --Fs {P}/5_higgsDecay --Fs {P}/2lss_Top-tagged_16 --Fs {P}/2lss_NoTop-tagged_16 --mcc ttH-multilepton/lepchoice-ttH-FO.txt -L ttH-multilepton/functionsTTH.cc --mcc ttH-multilepton/mcc-METFixEE2017.txt -p ttH --tree NanoAOD ttH-multilepton/mca-2lss-mc.txt ./2lss_tight_12.txt ./testing_diff_cuts_12

#python skimTreesNew.py -P /nfs/user/pvischia/tth/v5pre/NanoTrees_TTH_300519_v5pre_skim2LSS/2016 --skim-friends --Fs {P}/0_jmeUnc_v1 --Fs {P}/1_lepJetBTagDeepFlav_v1 --Fs {P}/2_triggerSequence_v1 --Fs {P}/2_triggerSequence_v2 --Fs {P}/3_recleaner_v1 --Fs {P}/3_recleaner_v2 --FMCs {P}/4_btag --FMCs {P}/4_btag_v2 --FMCs {P}/4_leptonSFs_v0 --FMCs {P}/0_mcFlags_v0 --Fs {P}/6_BDThtt --Fs {P}/5_higgsDecay --Fs {P}/2lss_Top-tagged_16 --Fs {P}/2lss_NoTop-tagged_16 --mcc ttH-multilepton/lepchoice-ttH-FO.txt -L ttH-multilepton/functionsTTH.cc --mcc ttH-multilepton/mcc-METFixEE2017.txt -p ttH --tree NanoAOD ttH-multilepton/mca-2lss-mc.txt ./2lss_tight_13.txt ./testing_diff_cuts_13

#python skimTreesNew.py -P /nfs/user/pvischia/tth/v5pre/NanoTrees_TTH_300519_v5pre_skim2LSS/2016 --skim-friends --Fs {P}/0_jmeUnc_v1 --Fs {P}/1_lepJetBTagDeepFlav_v1 --Fs {P}/2_triggerSequence_v1 --Fs {P}/2_triggerSequence_v2 --Fs {P}/3_recleaner_v1 --Fs {P}/3_recleaner_v2 --FMCs {P}/4_btag --FMCs {P}/4_btag_v2 --FMCs {P}/4_leptonSFs_v0 --FMCs {P}/0_mcFlags_v0 --Fs {P}/6_BDThtt --Fs {P}/5_higgsDecay --Fs {P}/2lss_Top-tagged_16 --Fs {P}/2lss_NoTop-tagged_16 --mcc ttH-multilepton/lepchoice-ttH-FO.txt -L ttH-multilepton/functionsTTH.cc --mcc ttH-multilepton/mcc-METFixEE2017.txt -p ttH --tree NanoAOD ttH-multilepton/mca-2lss-mc.txt ./2lss_tight_14.txt ./testing_diff_cuts_14

#python skimTreesNew.py -P /nfs/user/pvischia/tth/v5pre/NanoTrees_TTH_300519_v5pre_skim2LSS/2016 --skim-friends --Fs {P}/0_jmeUnc_v1 --Fs {P}/1_lepJetBTagDeepFlav_v1 --Fs {P}/2_triggerSequence_v1 --Fs {P}/2_triggerSequence_v2 --Fs {P}/3_recleaner_v1 --Fs {P}/3_recleaner_v2 --FMCs {P}/4_btag --FMCs {P}/4_btag_v2 --FMCs {P}/4_leptonSFs_v0 --FMCs {P}/0_mcFlags_v0 --Fs {P}/6_BDThtt --Fs {P}/5_higgsDecay --Fs {P}/2lss_Top-tagged_16 --Fs {P}/2lss_NoTop-tagged_16 --mcc ttH-multilepton/lepchoice-ttH-FO.txt -L ttH-multilepton/functionsTTH.cc --mcc ttH-multilepton/mcc-METFixEE2017.txt -p ttH --tree NanoAOD ttH-multilepton/mca-2lss-mc.txt ./2lss_tight_15.txt ./testing_diff_cuts_15

#python skimTreesNew.py -P /nfs/user/pvischia/tth/v5pre/NanoTrees_TTH_300519_v5pre_skim2LSS/2016 --skim-friends --Fs {P}/0_jmeUnc_v1 --Fs {P}/1_lepJetBTagDeepFlav_v1 --Fs {P}/2_triggerSequence_v1 --Fs {P}/2_triggerSequence_v2 --Fs {P}/3_recleaner_v1 --Fs {P}/3_recleaner_v2 --FMCs {P}/4_btag --FMCs {P}/4_btag_v2 --FMCs {P}/4_leptonSFs_v0 --FMCs {P}/0_mcFlags_v0 --Fs {P}/6_BDThtt --Fs {P}/5_higgsDecay --Fs {P}/2lss_Top-tagged_16 --Fs {P}/2lss_NoTop-tagged_16 --mcc ttH-multilepton/lepchoice-ttH-FO.txt -L ttH-multilepton/functionsTTH.cc --mcc ttH-multilepton/mcc-METFixEE2017.txt -p ttH --tree NanoAOD ttH-multilepton/mca-2lss-mc.txt ./2lss_tight_16.txt ./testing_diff_cuts_16

#python skimTreesNew.py -P /nfs/user/pvischia/tth/v5pre/NanoTrees_TTH_300519_v5pre_skim2LSS/2016 --skim-friends --Fs {P}/0_jmeUnc_v1 --Fs {P}/1_lepJetBTagDeepFlav_v1 --Fs {P}/2_triggerSequence_v1 --Fs {P}/2_triggerSequence_v2 --Fs {P}/3_recleaner_v1 --Fs {P}/3_recleaner_v2 --FMCs {P}/4_btag --FMCs {P}/4_btag_v2 --FMCs {P}/4_leptonSFs_v0 --FMCs {P}/0_mcFlags_v0 --Fs {P}/6_BDThtt --Fs {P}/5_higgsDecay --Fs {P}/2lss_Top-tagged_16 --Fs {P}/2lss_NoTop-tagged_16 --mcc ttH-multilepton/lepchoice-ttH-FO.txt -L ttH-multilepton/functionsTTH.cc --mcc ttH-multilepton/mcc-METFixEE2017.txt -p ttH --tree NanoAOD ttH-multilepton/mca-2lss-mc.txt ./2lss_tight_17.txt ./testing_diff_cuts_17
