OPTS=" -e -f -j 4 --s2v --tree treeProducerSusyGenLevelOnly susy-sos/gen-level/mca.txt susy-sos/gen-level/cuts.txt susy-sos/gen-level/plots.txt"
RATIO0=" --showRatio --maxRatioRange 0.5 1.49 --fixRatioRange --ratioDen CMS_Pow --ratioNums .* "
RATIO1=" --showRatio --maxRatioRange 0.5 1.49 --fixRatioRange --ratioDen aMC440 --ratioNums .* -p aMC440,MG440,Phw "
#python mcPlots.py $* ${OPTS} ${RATIO0} --plotmode=nostack --pdir plots/80X/sos/gen-level/all      -X M50 --xp aMC440,MG440,Phw440
#python mcPlots.py $* ${OPTS} ${RATIO0} --plotmode=norm    --pdir plots/80X/sos/gen-level/all_norm -X M50 --xp aMC440,MG440,Phw440
#python mcPlots.py $* ${OPTS} ${RATIO0} --plotmode=nostack --pdir plots/80X/sos/gen-level/m50     -p CMS_Pow,aMC,MG,Phw --xP mll_low
#python mcPlots.py $* ${OPTS} ${RATIO0} --plotmode=norm    --pdir plots/80X/sos/gen-level/m50_norm -p CMS_Pow,aMC,MG,Phw --xP mll_low
python mcPlots.py $* ${OPTS} ${RATIO1} --plotmode=nostack --pdir plots/80X/sos/gen-level/m520      -R M50 M520 "m2l > 5 && m2l < 20" 
python mcPlots.py $* ${OPTS} ${RATIO1} --plotmode=norm    --pdir plots/80X/sos/gen-level/m520_norm -R M50 M520 "m2l > 5 && m2l < 20"
RATION=" --showRatio --maxRatioRange 0.2 1.79 --fixRatioRange --ratioDen aMC --ratioNums aMC440 -p aMC,aMC440 --sp aMC440"
RATIOM=" --showRatio --maxRatioRange 0.2 1.79 --fixRatioRange --ratioDen MG --ratioNums MG440 -p MG,MG440 --sp MG440"
#python mcPlots.py $* ${OPTS} ${RATION} --plotmode=nostack --pdir plots/80X/sos/gen-level/aMC_match -X M50 --sP 'mll.*'
#python mcPlots.py $* ${OPTS} ${RATIOM} --plotmode=nostack --pdir plots/80X/sos/gen-level/MG_match -X M50 --sP 'mll.*'
RATION2=" --showRatio --maxRatioRange 0.2 1.79 --fixRatioRange --ratioDen aMC --ratioNums aMC440,CMS_Pow -p aMC,aMC440,CMS_Pow --sp aMC440,CMS_Pow"
RATIOM2=" --showRatio --maxRatioRange 0.2 1.79 --fixRatioRange --ratioDen MG --ratioNums MG440,CMS_Pow -p MG,MG440,CMS_Pow --sp MG440,CMS_Pow"
#python mcPlots.py $* ${OPTS} ${RATION2} --plotmode=nostack --pdir plots/80X/sos/gen-level/aMC_match_2 -X M50 --sP 'mll.*'
#python mcPlots.py $* ${OPTS} ${RATIOM2} --plotmode=nostack --pdir plots/80X/sos/gen-level/MG_match_2 -X M50 --sP 'mll.*'
#python mcPlots.py $* ${OPTS} ${RATION2} --plotmode=nostack --pdir plots/80X/sos/gen-level/aMC_match_2b -X M50 --sP 'mll.*' --scale-process aMC.* 0.942
#python mcPlots.py $* ${OPTS} ${RATIOM2} --plotmode=nostack --pdir plots/80X/sos/gen-level/MG_match_2b -X M50 --sP 'mll.*'  --scale-process MG.* 1.236
RATION3=" --showRatio --maxRatioRange 0.75 1.25 --fixRatioRange --ratioDen aMC --ratioNums CMS_p_aMC -p aMC,CMS_p_aMC --sp CMS_p_aMC --fitRatio 0"
#python mcPlots.py $* ${OPTS} ${RATION3} --plotmode=nostack --pdir plots/80X/sos/gen-level/aMC_match_3 -X M50 --sP 'mll.*'
RATIOP1=" --showRatio --maxRatioRange 0.2 1.79 --fixRatioRange --ratioDen Phw4inf --ratioNums Phw440,CMS_Pow -p Phw4inf,Phw440,CMS_Pow --sp Phw440,CMS_Pow"
RATIOP2=" --showRatio --maxRatioRange 0.2 1.79 --fixRatioRange --ratioDen Phw --ratioNums CMS_Pow -p Phw,CMS_Pow --sp CMS_Pow"
#python mcPlots.py $* ${OPTS} ${RATIOP1} --plotmode=nostack --pdir plots/80X/sos/gen-level/Phw_match_1 -X M50 --sP 'mll.*'
#python mcPlots.py $* ${OPTS} ${RATIOP2} --plotmode=nostack --pdir plots/80X/sos/gen-level/Phw_match_2 -X M50 --sP 'mll.*'
