// Class: ReadFisher
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : Fisher::Fisher
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : mdunser
Date           : Thu Apr  5 14:33:41 2018
Host           : Linux vocms0301.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/m/mdunser/public/cmssw/dpsww2018/CMSSW_8_0_25/src/CMGTools/DPS13TeV/python/plotter
Training events: 171955
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
Method: "Fisher" [Discrimination method]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
LepGood_pt[0]                 LepGood_pt_0_                 LepGood_pt[0]                 p_{T1}                        F                                 'F'    [25.0011577606,1245.96618652]
LepGood_pt[1]                 LepGood_pt_1_                 LepGood_pt[1]                 p_{T2}                        F                                 'F'    [20.0000228882,870.709472656]
met_pt                        met_pt                        met_pt                        met_pt                                                          'F'    [15.0004262924,1130.2244873]
mt2davis(LepGood_pt[0],LepGood_eta[0],LepGood_phi[0],LepGood_pt[1],LepGood_eta[1],LepGood_phi[1],met_pt,met_phi) mt2davis_LepGood_pt_0_,LepGood_eta_0_,LepGood_phi_0_,LepGood_pt_1_,LepGood_eta_1_,LepGood_phi_1_,met_pt,met_phi_ mt2davis(LepGood_pt[0],LepGood_eta[0],LepGood_phi[0],LepGood_pt[1],LepGood_eta[1],LepGood_phi[1],met_pt,met_phi) MT2_{ll}                                                                                                         F                                                                                                                    'F'    [0,895.459533691]
mt_2(LepGood_pt[0],LepGood_phi[0],LepGood_pt[1],LepGood_phi[1]) mt_2_LepGood_pt_0_,LepGood_phi_0_,LepGood_pt_1_,LepGood_phi_1__ mt_2(LepGood_pt[0],LepGood_phi[0],LepGood_pt[1],LepGood_phi[1]) MT l1 l2                                                        F                                                                   'F'    [0,1835.48022461]
mt_2(LepGood_pt[0],LepGood_phi[0],met_pt,met_phi) mt_2_LepGood_pt_0_,LepGood_phi_0_,met_pt,met_phi_ mt_2(LepGood_pt[0],LepGood_phi[0],met_pt,met_phi) MT l1 met                                         F                                                     'F'    [0,2185.57006836]
abs(deltaPhi(LepGood_phi[0],LepGood_phi[1])) abs_deltaPhi_LepGood_phi_0_,LepGood_phi_1___ abs(deltaPhi(LepGood_phi[0],LepGood_phi[1])) #Delta #phi l1 l2                            F                                                'F'    [1.40070915222e-06,3.14159059525]
abs(deltaPhi(LepGood_phi[1],met_phi)) abs_deltaPhi_LepGood_phi_1_,met_phi__ abs(deltaPhi(LepGood_phi[1],met_phi)) #Delta #phi l2 met                    F                                         'F'    [1.37090682983e-05,3.14155507088]
abs(deltaPhi(phi_2(LepGood_pt[0],LepGood_eta[0],LepGood_phi[0],LepGood_mass[0],LepGood_pt[1],LepGood_eta[1],LepGood_phi[1],LepGood_mass[1]),LepGood_phi[1])) abs_deltaPhi_phi_2_LepGood_pt_0_,LepGood_eta_0_,LepGood_phi_0_,LepGood_mass_0_,LepGood_pt_1_,LepGood_eta_1_,LepGood_phi_1_,LepGood_mass_1__,LepGood_phi_1___ abs(deltaPhi(phi_2(LepGood_pt[0],LepGood_eta[0],LepGood_phi[0],LepGood_mass[0],LepGood_pt[1],LepGood_eta[1],LepGood_phi[1],LepGood_mass[1]),LepGood_phi[1])) d#phi(ll,l2)                                                                                                                                                 F                                                                                                                                                                'F'    [1.40070915222e-06,3.14159059525]
LepGood_eta[0]*LepGood_eta[1]   LepGood_eta_0__T_LepGood_eta_1_ LepGood_eta[0]*LepGood_eta[1]   #eta_{1}*#eta_{2}               F                                   'F'    [-5.96885728836,6.21743297577]
abs(LepGood_eta[0]+LepGood_eta[1])   abs_LepGood_eta_0__P_LepGood_eta_1__ abs(LepGood_eta[0]+LepGood_eta[1])   abs(#eta_{1}+#eta_{2})               F                                        'F'    [3.96370887756e-06,4.98696899414]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadFisher : public IClassifierReader {

 public:

   // constructor
   ReadFisher( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadFisher" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "LepGood_pt[0]", "LepGood_pt[1]", "met_pt", "mt2davis(LepGood_pt[0],LepGood_eta[0],LepGood_phi[0],LepGood_pt[1],LepGood_eta[1],LepGood_phi[1],met_pt,met_phi)", "mt_2(LepGood_pt[0],LepGood_phi[0],LepGood_pt[1],LepGood_phi[1])", "mt_2(LepGood_pt[0],LepGood_phi[0],met_pt,met_phi)", "abs(deltaPhi(LepGood_phi[0],LepGood_phi[1]))", "abs(deltaPhi(LepGood_phi[1],met_phi))", "abs(deltaPhi(phi_2(LepGood_pt[0],LepGood_eta[0],LepGood_phi[0],LepGood_mass[0],LepGood_pt[1],LepGood_eta[1],LepGood_phi[1],LepGood_mass[1]),LepGood_phi[1]))", "LepGood_eta[0]*LepGood_eta[1]", "abs(LepGood_eta[0]+LepGood_eta[1])" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadFisher() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   double              fFisher0;
   std::vector<double> fFisherCoefficients;
};

inline void ReadFisher::Initialize() 
{
   fFisher0 = -1.25364516284e+15;
   fFisherCoefficients.push_back( -0.00289165317017 );
   fFisherCoefficients.push_back( -0.00245599794084 );
   fFisherCoefficients.push_back( -0.00080496404466 );
   fFisherCoefficients.push_back( 0.000167586827635 );
   fFisherCoefficients.push_back( -0.00250532628172 );
   fFisherCoefficients.push_back( -0.00130784417586 );
   fFisherCoefficients.push_back( -7.14289215766e+14 );
   fFisherCoefficients.push_back( -0.00317361254104 );
   fFisherCoefficients.push_back( 1.44252237317e+15 );
   fFisherCoefficients.push_back( -0.0975007933113 );
   fFisherCoefficients.push_back( 0.0684774876521 );

   // sanity check
   if (fFisherCoefficients.size() != fNvars) {
      std::cout << "Problem in class \"" << fClassName << "\"::Initialize: mismatch in number of input values"
                << fFisherCoefficients.size() << " != " << fNvars << std::endl;
      fStatusIsClean = false;
   }         
}

inline double ReadFisher::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double retval = fFisher0;
   for (size_t ivar = 0; ivar < fNvars; ivar++) {
      retval += fFisherCoefficients[ivar]*inputValues[ivar];
   }

   return retval;
}

// Clean up
inline void ReadFisher::Clear() 
{
   // clear coefficients
   fFisherCoefficients.clear(); 
}
   inline double ReadFisher::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
